# Generated by Django 5.2.4 on 2025-07-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeInt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeprod',
            name='stripeId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
