# Generated by Django 5.2.4 on 2025-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeInt', '0002_alter_stripeprod_stripeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
