# Generated by Django 5.2.4 on 2025-07-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeInt', '0003_stripeprod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprod',
            name='defaultPriceId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
