# Generated by Django 5.2.6 on 2025-09-10 09:37

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stripeInt', '0005_alter_stripeprod_defaultpriceid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tutoring.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketItems', to='stripeInt.stripeprod')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_length', models.IntegerField(default=1)),
                ('tutor', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('Junior Maths', 'Junior Maths'), ('11 Advanced', '11 Advanced'), ('11 Ext 1', '11 Ext 1'), ('12 Advanced', '12 Advanced'), ('12 Ext 1', '12 Ext 1'), ('12 Ext 2', '12 Ext 2')], max_length=20, null=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('time_of_day', models.TimeField(null=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('image_upload', models.FileField(blank=True, null=True, upload_to='tmp/')),
                ('associated_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_groups', to='stripeInt.stripeprod')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tutoring.group')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripeId', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('half-termly', 'Half-Termly'), ('termly', 'Termly')], default='half-termly', max_length=20)),
                ('basket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.basket')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Resource')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tutoring.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(related_name='tutoringStudents', to='tutoring.group')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tutoring.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tutoring.lesson')),
                ('tutoringStudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons_attended', to='tutoring.tutoringstudent')),
            ],
        ),
    ]
