# Generated by Django 5.2.4 on 2025-07-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
