# Generated by Django 5.2.6 on 2025-09-12 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_tutoringstudent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tutoringStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons_attended', to='tutoring.tutoringstudent'),
        ),
    ]
