# Generated by Django 5.2.4 on 2025-07-08 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_basketitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='basket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.basket'),
        ),
    ]
