# Generated by Django 5.2.4 on 2025-07-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_parent_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='payment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('half-termly', 'Half-Termly'), ('termly', 'Termly')], default='half-termly', max_length=20),
        ),
    ]
