# Generated by Django 5.2.4 on 2025-09-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_parent_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
