# Generated by Django 5.2.4 on 2025-09-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_group_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_upload',
            field=models.FileField(blank=True, null=True, upload_to='tmp/'),
        ),
    ]
