# Generated by Django 5.2.6 on 2025-10-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
