# Generated by Django 5.2.6 on 2025-10-10 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_attendance_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringstudent',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringstudent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringstudent',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
