# Generated by Django 5.2.4 on 2025-09-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_group_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[('Junior Maths', 'Junior Maths'), ('11 Advanced', '11 Advanced'), ('11 Ext 1', '11 Ext 1'), ('12 Advanced', '12 Advanced'), ('12 Ext 1', '12 Ext 1'), ('12 Ext 2', '12 Ext 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='time_of_day',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.CharField(default='Pri', max_length=50),
            preserve_default=False,
        ),
    ]
