# Generated by Django 5.2.6 on 2025-10-11 07:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_tutoringstudent_active_tutoringstudent_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeInvoiceId', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='group',
            name='lesson_length',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='attendance',
            name='local_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='tutoring.localinvoice'),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
