# Generated by Django 5.2.4 on 2025-09-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_group_course_group_day_of_week_group_time_of_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='invoiced',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons_attended', to='tutoring.student'),
        ),
    ]
