# Generated by Django 5.2.4 on 2025-09-10 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_rename_invoiced_attendance_paid_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tutoring.group'),
        ),
    ]
