# Generated by Django 5.2.6 on 2025-10-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_localinvoice_remove_basketitem_basket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lesson_length',
            field=models.IntegerField(),
        ),
    ]
