# Generated by Django 5.2.4 on 2025-09-10 05:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_lesson_file_lesson_notes_alter_lesson_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Resource'),
        ),
    ]
