# Generated by Django 5.2.6 on 2025-10-12 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_alter_group_lesson_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localinvoice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='amount_due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='customer_stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='status',
            field=models.CharField(default='open', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localinvoice',
            name='status_transitions_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localinvoice',
            name='stripeInvoiceId',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='localinvoice',
            index=models.Index(fields=['status', 'status_transitions_paid_at'], name='tutoring_lo_status_670c22_idx'),
        ),
        migrations.AddIndex(
            model_name='localinvoice',
            index=models.Index(fields=['created'], name='tutoring_lo_created_e4002d_idx'),
        ),
    ]
