# Generated by Django 5.2.4 on 2025-09-10 05:24

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_remove_lesson_file_lesson_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='resource',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Resource')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tutoring.lesson')),
            ],
        ),
    ]
