# Generated by Django 5.2.4 on 2025-09-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_remove_lesson_resource_alter_lesson_notes_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='homework',
            field=models.BooleanField(default=False),
        ),
    ]
