# Generated by Django 5.2.6 on 2025-10-14 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_term_year_week_term_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TutoringYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='term',
            name='year',
        ),
        migrations.RemoveField(
            model_name='week',
            name='term',
        ),
        migrations.CreateModel(
            name='TutoringWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='tutoring.tutoringterm')),
            ],
        ),
        migrations.AddField(
            model_name='tutoringterm',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='tutoring.tutoringyear'),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
