# Generated by Django 5.2.6 on 2025-10-14 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0014_tutoringterm_tutoringyear_remove_term_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='tutoring.tutoringterm'),
        ),
    ]
