# Generated by Django 5.2.6 on 2025-10-14 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0015_lesson_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringterm',
            name='previousTerm',
            field=models.ForeignKey(blank=True, help_text='The term immediately before this term', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_term', to='tutoring.tutoringterm'),
        ),
    ]
