# Generated by Django 5.2.6 on 2025-10-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0016_tutoringterm_previousterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='term',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tutoringWeek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='tutoring.tutoringweek'),
        ),
    ]
