# Generated by Django 5.2.6 on 2025-10-15 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0017_remove_lesson_term_lesson_tutoringweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringweek',
            name='monday_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringweek',
            name='sunday_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
