# Generated by Django 5.2.6 on 2025-10-15 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0018_tutoringweek_monday_date_tutoringweek_sunday_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoringweek',
            options={'ordering': ['term', 'index']},
        ),
        migrations.AddField(
            model_name='tutoringterm',
            name='end_date',
            field=models.DateField(blank=True, help_text='Sunday of the last week of the term (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='tutoringterm',
            name='start_date',
            field=models.DateField(blank=True, help_text='Monday of the first week of the term', null=True),
        ),
        migrations.AlterField(
            model_name='tutoringterm',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tutoring.tutoringyear'),
        ),
        migrations.AlterField(
            model_name='tutoringweek',
            name='monday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutoringweek',
            name='sunday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tutoringweek',
            index=models.Index(fields=['monday_date', 'sunday_date'], name='tutoring_tu_monday__7011b4_idx'),
        ),
    ]
