name: Test Coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.cicd
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      SECRET_KEY: test-secret-key-for-ci
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install coverage psycopg2-binary
    
    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        coverage run --source='.' manage.py test
        coverage report --fail-under=80
        coverage xml
  